source 'https://rubygems.org'

gem 'sinatra'
gem 'thin'

group :development do
  gem 'rerun'
  gem 'rubocop'
end

group :development, :test do
  gem 'byebug'
end

group :test do
  gem 'minitest'
  gem 'capybara'
  gem 'capybara-screenshot'
end
